src/Entity/Consultation.php
<?php

namespace App\Entity;

use App\Repository\ConsultationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ConsultationRepository::class)
 */
class Consultation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_heure;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $motif;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $etat;

    /**
     * @ORM\Column(type="time")
     */
    private $duree;

    /**
     * @ORM\OneToMany(targetEntity=HistoriqueConsultation::class, mappedBy="la_consultation")
     */
    private $historique_consultations;

    /**
     * @ORM\ManyToOne(targetEntity=Medecin::class, inversedBy="consultations")
     */
    private $medecin;

    /**
     * @ORM\ManyToOne(targetEntity=Patient::class, inversedBy="consultations")
     */
    private $patient;

    public function __construct()
    {
        $this->historique_consultations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateHeure(): ?\DateTimeInterface
    {
        return $this->date_heure;
    }

    public function setDateHeure(\DateTimeInterface $date_heure): self
    {
        $this->date_heure = $date_heure;

        return $this;
    }

    public function getMotif(): ?string
    {
        return $this->motif;
    }

    public function setMotif(string $motif): self
    {
        $this->motif = $motif;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(\DateTimeInterface $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    /**
     * @return Collection|HistoriqueConsultation[]
     */
    public function getHistoriqueConsultations(): Collection
    {
        return $this->historique_consultations;
    }

    public function addHistoriqueConsultation(HistoriqueConsultation $historiqueConsultation): self
    {
        if (!$this->historique_consultations->contains($historiqueConsultation)) {
            $this->historique_consultations[] = $historiqueConsultation;
            $historiqueConsultation->setLaConsultation($this);
        }

        return $this;
    }

    public function removeHistoriqueConsultation(HistoriqueConsultation $historiqueConsultation): self
    {
        if ($this->historique_consultations->removeElement($historiqueConsultation)) {
            // set the owning side to null (unless already changed)
            if ($historiqueConsultation->getLaConsultation() === $this) {
                $historiqueConsultation->setLaConsultation(null);
            }
        }

        return $this;
    }

    public function getMedecin(): ?medecin
    {
        return $this->medecin;
    }

    public function setMedecin(?medecin $medecin): self
    {
        $this->medecin = $medecin;

        return $this;
    }

    public function getPatient(): ?patient
    {
        return $this->patient;
    }

    public function setPatient(?patient $patient): self
    {
        $this->patient = $patient;

        return $this;
    }
}

src/Entity/Patient.php
<?php

namespace App\Entity;

use App\Repository\PatientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PatientRepository::class)
 */
class Patient extends Utilisateur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity=Consultation::class, mappedBy="patient")
     */
    protected $consultations;

    public function __construct()
    {
        $this->consultations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Consultation[]
     */
    public function getConsultations(): Collection
    {
        return $this->consultations;
    }

    public function addConsultation(Consultation $consultation): self
    {
        if (!$this->consultations->contains($consultation)) {
            $this->consultations[] = $consultation;
            $consultation->setPatient($this);
        }

        return $this;
    }

    public function removeConsultation(Consultation $consultation): self
    {
        if ($this->consultations->removeElement($consultation)) {
            // set the owning side to null (unless already changed)
            if ($consultation->getPatient() === $this) {
                $consultation->setPatient(null);
            }
        }

        return $this;
    }
}

src/Controller/PatientController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Patient;
use App\Entity\Consultation;
use Symfony\Component\HttpFoundation\Request;
use App\Form\ConsultationType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PatientController extends AbstractController
{
	
	/**
     * @Route("/patient", name="patient")
     */
    public function index(): Response
    {
        $user = $this->getUser();
        $id = $user->getInfo();        ;
        $repository=$this->getDoctrine()->getRepository(Patient::class);
        $lePatient=$repository->find($id); 
        return $this->render('patient/index.html.twig', ['patient' => $lePatient, 'id' => $id
        ]);
    }
	
    /**
     * @Route("/rendezvous/{id}", name="rendezvous")
     */
    public function rendezvous($id): Response
    {
        $repository=$this->getDoctrine()->getRepository(Consultation::class);
        $leRdv=$repository->find($id); 
        return $this->render('patient/rendezvous.html.twig', ['rendezvous' => $leRdv,]);
    }

    /**
     * @Route("/removeConsultation/{id}", name="removeConsultation")
     */
     public function removeConsultation($id, Request $request){
            
            $repository=$this->getDoctrine()->getRepository(Consultation::Class);
            $rdv=$repository->find($id);           
            $em=$this->getDoctrine()->getManager();         
            $em->remove($rdv);
            $em->flush();
            return $this->redirectToRoute('patient');
     }

     /**
     * @Route("/modifConsultation/{id}", name="modifConsultation")
     */
     public function modifConsultation($id, Request $request){
        $em=$this->getDoctrine()->getManager();
        $repository=$this->getDoctrine()->getRepository(Consultation::class);
        $consultation=$repository->find($id);
        $form=$this->createForm(ConsultationType::class,$consultation);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $consultation=$form->getData();
            $em=$this->getDoctrine()->getManager();
            $em->persist($consultation);
            $em->flush();
            return $this->redirectToRoute('accueil');
        }   
        return $this->render('patient/modifConsultation.html.twig', array(
            'form' => $form->createView(),
        ));
     }

     /**
     * @Route("/annulerConsultation/{id}", name="annulerConsultation")
     */
     public function annulerConsultation($id){
        $em=$this->getDoctrine()->getManager();
        $repository=$this->getDoctrine()->getRepository(Consultation::class);
        $lesConsultations=$repository->findAll();
        $consultation=$repository->find($id);
        $consultation->setEtat('Annulee');
        $em->persist($consultation);
        $em->flush();
        return $this->render('consultation/validation.html.twig', [
            'consultations' => $lesConsultations,
        ]);
     }


	
}

templates/patient/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PatientController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1> Rendez-vous de {{patient.getEmail()}} </h1>
       
        <table>
            <tr>
                <th>ID</th> 
                <th>Date Heure</th> 
                <th>Médecin</th> 
                <th>Motif</th> 
                <th>Etat</th> 
            </tr>
        {% for rdv in patient.getConsultations %}            
            <tr>
            <td> {{rdv.id}} </td>
            <td> {{rdv.dateHeure | date('d/m/Y H:m')}} </td> 
            <td> {{rdv.getMedecin().getEmail()}} </td>
            <td> {{rdv.motif}} </td> 
            <td> {{rdv.etat}} </td>
            <td> <a href="{{path('modifConsultation',{id:rdv.id})}}"> Modifier </a> | <a href="{{path('removeConsultation',{id:rdv.id})}}"> Supprimer </a> </td> 
            </tr>         
        {% else %}
            Aucun rendez vous trouvé
        {% endfor %}
            </table>
</div>
{% endblock %}

templates/patient/modifConsultation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une consultation{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Modifier une consultation POUR UN PATIENT</h1>
	{{form_start(form)}}
	{{form_widget(form)}}
	{{form_end(form)}}
</div>
{% endblock %}

templates/patient/rendezvous.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PatientController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1> Rendez vous n°{{rendezvous.id}} </h1>

    

</div>
{% endblock %}